version: '3.8'

services:
  backend:
    build: ./server
    container_name: mern-backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb+srv://<user>:<password>@cluster0.mongodb.net/mern-demo?retryWrites=true&w=majority

  frontend:
    build: ./client
    container_name: mern-frontend
    ports:
      - "3000:3000"